### PR TITLE
Updated instructions for dependancies and correct URL

### PR DESCRIPTION
**Pull request by snowzach**
I tested this repo.xml last night.. It works however you need to use https as github will try to redirect endlessly... In order to pull down https you also need IO::Socket::SSL installed.

### CODE REVIEW

**Comment by mark-e-mark** [comment]
I tried adding this to my settings and My LMS installation won't accept HTTPS in the Plugins repository entry, only HTTP.  I haven't updated in awhile, so that may be the issue. Logitech Media Server Version: 7.9.0 - 1455894713.

**Comment by snowzach** [comment]
Is it literally not accepting or just not working? I am using 7.8 and it allowed https. You need IO::Socket::SSL installed or it will give a bunch of errors in the log.

**Comment by mark-e-mark** [comment]
The web settings page will not save https. That is, I click apply and my entry with HTTPS is no longer in the input box. I can save `http://squeezeboxgooglemusic.github.io/squeezebox-googlemusic/repository/repo.xml`. 

[Pic here](https://drive.google.com/open?id=0B8_eSJx_JqXDbkZBNGZlTlFtcDQ)

**Comment by snowzach** [comment]
I had a very similar issue. Close all your browser windows, go back to the main page, hit settings again, paste in the link and apply it. Something with the the browser window data being stale. (At least with 7.8)

**Comment by mark-e-mark** [comment]
Thanks for the suggestion @snowzach however it didn't work for me. I think this may be my own installation issue as I am suddenly no longer able to login to Google Services. Plugin page for Google Music on SBS shows not logged in. I tried new password and updated GSF ID but no go. I'll uninstall the plugin and see if I can start fresh.
Log:

[16-08-25 09:14:26.5689] Plugins::GoogleMusic::Settings::handler (75) Not able to login to Google Play Music: exceptions.TypeError: login() takes exactly 4 arguments (3 given) at (eval 1169) line 176.
[16-08-25 09:14:44.9261] Slim::Utils::Timers::**ANON** (273) Error: Timer Plugins::GoogleMusic::Settings::_restartServer failed: Can't use an undefined value as an ARRAY reference at /usr/share/perl5/Slim/Utils/OS/Unix.pm line 147.
[16-08-25 09:15:15.7245] Plugins::GoogleMusic::AllAccess::getStations (565) Not able to get user created radio stations: NotLoggedIn:  at line 757

**Comment by mark-e-mark** [comment]
Restarted LMS and it logged into Google Play music, with the plugin from 
`http://nick7634.github.io/squeezebox-googlemusic/repository/repo.xml`

Still can't add https repo into setttings box. Clicking apply removes it without attempting to restart LMS. I added the http version of the github repo and restarted from CLI, but I don't think anything was downloaded. Google Music is working. 
`http://squeezebox-googlemusic.github.io/squeezebox-googlemusic/repository/repo.xml`

Do you see requests from IP 70.117.123.210 (or something close)?

**Comment by mark-e-mark** [comment]
Since both of you have 7.8 and I'm on 7.9, I have to think that's the issue. I tried adding the HTTPS repo in a Firefox window and got the same result as above in Chrome.

**Comment by snowzach** [comment]
Do you see any messages in the server.log file?

**Comment by snowzach** [comment]
Hey @askvictor .. are you still working with this project?

**Comment by askvictor** [comment]
Yep,  on and off.

**Comment by askvictor** [comment]
Should probably also update the github-pages page (https://github.com/squeezebox-googlemusic/squeezebox-googlemusic/blob/gh-pages/index.html) - would be nice if there were a way to keep that at the readme in sync, but I have no time to work on that atm

**Pull request merged**
